apiVersion: v1
kind: Service
metadata:
  name: svc-apps-apptier-api
  namespace: swiftcaps-apps
spec:
  selector:
    app: apiapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-swiftcapsapps-apptier
  namespace: swiftcaps-apps
data:
  port: "8080"
  resp: "Swiftcaps/apps/apptier received request"
  oocSvcIPOrFQDN: "172.19.0.1"
  oocSvcPort: "8080"
  oocSvcPath: "/api/resp"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiapp
  namespace: swiftcaps-apps
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: apiapp
  template:
    metadata:
      labels:
        tier: app
        app: apiapp
        project: swiftcaps
    spec:
      containers:
      - name: apiapp
        image: acrswiftoffice.azurecr.io/networkpolicy:api-0.0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
